// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package notifications.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the Notifications module
	public static void aCT_MarkAsRead(IContext context, notifications.proxies.Notification _notification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Notification", _notification == null ? null : _notification.getMendixObject());
		Core.microflowCall("Notifications.ACT_MarkAsRead").withParams(params).execute(context);
	}
	public static void aCT_ShowRequest(IContext context, notifications.proxies.Notification _notification)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Notification", _notification == null ? null : _notification.getMendixObject());
		Core.microflowCall("Notifications.ACT_ShowRequest").withParams(params).execute(context);
	}
}