// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package generalextensions.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the GeneralExtensions module
	public static void aCT_Registration_CreateAccount(IContext context, generalextensions.proxies.Registration _registration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Registration", _registration == null ? null : _registration.getMendixObject());
		Core.microflowCall("GeneralExtensions.ACT_Registration_CreateAccount").withParams(params).execute(context);
	}
	public static void manageMyAccount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("GeneralExtensions.ManageMyAccount").withParams(params).execute(context);
	}
	public static boolean sUB_Registration_Validate(IContext context, generalextensions.proxies.Registration _registration)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Registration", _registration == null ? null : _registration.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("GeneralExtensions.SUB_Registration_Validate").withParams(params).execute(context);
	}
}