// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package generalextensions.proxies;

public class ProfilePicture extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GeneralExtensions.ProfilePicture";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		ProfilePicture_Account("GeneralExtensions.ProfilePicture_Account");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProfilePicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "GeneralExtensions.ProfilePicture"));
	}

	protected ProfilePicture(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject profilePictureMendixObject)
	{
		super(context, profilePictureMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("GeneralExtensions.ProfilePicture", profilePictureMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a GeneralExtensions.ProfilePicture");
	}

	/**
	 * @deprecated Use 'ProfilePicture.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static generalextensions.proxies.ProfilePicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return generalextensions.proxies.ProfilePicture.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static generalextensions.proxies.ProfilePicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new generalextensions.proxies.ProfilePicture(context, mendixObject);
	}

	public static generalextensions.proxies.ProfilePicture load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return generalextensions.proxies.ProfilePicture.initialize(context, mendixObject);
	}

	public static java.util.List<generalextensions.proxies.ProfilePicture> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<generalextensions.proxies.ProfilePicture> result = new java.util.ArrayList<generalextensions.proxies.ProfilePicture>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//GeneralExtensions.ProfilePicture" + xpathConstraint))
			result.add(generalextensions.proxies.ProfilePicture.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ProfilePicture_Account
	 */
	public final administration.proxies.Account getProfilePicture_Account() throws com.mendix.core.CoreException
	{
		return getProfilePicture_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of ProfilePicture_Account
	 */
	public final administration.proxies.Account getProfilePicture_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ProfilePicture_Account.toString());
		if (identifier != null)
			result = administration.proxies.Account.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ProfilePicture_Account
	 * @param profilepicture_account
	 */
	public final void setProfilePicture_Account(administration.proxies.Account profilepicture_account)
	{
		setProfilePicture_Account(getContext(), profilepicture_account);
	}

	/**
	 * Set value of ProfilePicture_Account
	 * @param context
	 * @param profilepicture_account
	 */
	public final void setProfilePicture_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account profilepicture_account)
	{
		if (profilepicture_account == null)
			getMendixObject().setValue(context, MemberNames.ProfilePicture_Account.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ProfilePicture_Account.toString(), profilepicture_account.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final generalextensions.proxies.ProfilePicture that = (generalextensions.proxies.ProfilePicture) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "GeneralExtensions.ProfilePicture";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
