// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vacationmanagement.proxies;

public enum ENU_VacationRequestType
{
	Annual_Holiday_Paid_Paid_Time_Off__PTO_(new java.lang.String[][] { new java.lang.String[] { "en_US", "Annual Holiday Paid/Paid Time Off (PTO)" } }),
	Special_Leave(new java.lang.String[][] { new java.lang.String[] { "en_US", "Special Leave" } }),
	Parental_Leave(new java.lang.String[][] { new java.lang.String[] { "en_US", "Parental Leave" } }),
	Unpaid(new java.lang.String[][] { new java.lang.String[] { "en_US", "Unpaid" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private ENU_VacationRequestType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
