// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package vacationmanagement.proxies;

public class VacationRequestDay
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject vacationRequestDayMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "VacationManagement.VacationRequestDay";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Date("Date"),
		Hours("Hours"),
		VacationRequestDay_VacationRequest("VacationManagement.VacationRequestDay_VacationRequest");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public VacationRequestDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "VacationManagement.VacationRequestDay"));
	}

	protected VacationRequestDay(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vacationRequestDayMendixObject)
	{
		if (vacationRequestDayMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("VacationManagement.VacationRequestDay", vacationRequestDayMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a VacationManagement.VacationRequestDay");

		this.vacationRequestDayMendixObject = vacationRequestDayMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'VacationRequestDay.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static vacationmanagement.proxies.VacationRequestDay initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return vacationmanagement.proxies.VacationRequestDay.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static vacationmanagement.proxies.VacationRequestDay initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new vacationmanagement.proxies.VacationRequestDay(context, mendixObject);
	}

	public static vacationmanagement.proxies.VacationRequestDay load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return vacationmanagement.proxies.VacationRequestDay.initialize(context, mendixObject);
	}

	public static java.util.List<vacationmanagement.proxies.VacationRequestDay> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<vacationmanagement.proxies.VacationRequestDay> result = new java.util.ArrayList<vacationmanagement.proxies.VacationRequestDay>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//VacationManagement.VacationRequestDay" + xpathConstraint))
			result.add(vacationmanagement.proxies.VacationRequestDay.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of Hours
	 */
	public final java.lang.Integer getHours()
	{
		return getHours(getContext());
	}

	/**
	 * @param context
	 * @return value of Hours
	 */
	public final java.lang.Integer getHours(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Hours.toString());
	}

	/**
	 * Set value of Hours
	 * @param hours
	 */
	public final void setHours(java.lang.Integer hours)
	{
		setHours(getContext(), hours);
	}

	/**
	 * Set value of Hours
	 * @param context
	 * @param hours
	 */
	public final void setHours(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer hours)
	{
		getMendixObject().setValue(context, MemberNames.Hours.toString(), hours);
	}

	/**
	 * @return value of VacationRequestDay_VacationRequest
	 */
	public final vacationmanagement.proxies.VacationRequest getVacationRequestDay_VacationRequest() throws com.mendix.core.CoreException
	{
		return getVacationRequestDay_VacationRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of VacationRequestDay_VacationRequest
	 */
	public final vacationmanagement.proxies.VacationRequest getVacationRequestDay_VacationRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		vacationmanagement.proxies.VacationRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.VacationRequestDay_VacationRequest.toString());
		if (identifier != null)
			result = vacationmanagement.proxies.VacationRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of VacationRequestDay_VacationRequest
	 * @param vacationrequestday_vacationrequest
	 */
	public final void setVacationRequestDay_VacationRequest(vacationmanagement.proxies.VacationRequest vacationrequestday_vacationrequest)
	{
		setVacationRequestDay_VacationRequest(getContext(), vacationrequestday_vacationrequest);
	}

	/**
	 * Set value of VacationRequestDay_VacationRequest
	 * @param context
	 * @param vacationrequestday_vacationrequest
	 */
	public final void setVacationRequestDay_VacationRequest(com.mendix.systemwideinterfaces.core.IContext context, vacationmanagement.proxies.VacationRequest vacationrequestday_vacationrequest)
	{
		if (vacationrequestday_vacationrequest == null)
			getMendixObject().setValue(context, MemberNames.VacationRequestDay_VacationRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.VacationRequestDay_VacationRequest.toString(), vacationrequestday_vacationrequest.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return vacationRequestDayMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final vacationmanagement.proxies.VacationRequestDay that = (vacationmanagement.proxies.VacationRequestDay) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "VacationManagement.VacationRequestDay";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
